<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;    //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;        //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\enterprise_customer\Company as Company;        //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ValidateParam as ValidateParam;     //ValidateParam                 >> To validate the body form request
use \classes\middleware\ApiKey as ApiKey;                   //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim

    
    // Add new data company
    $app->post('/enterprise_customer/company/add', function (Request $request, Response $response) {
        $c = new Company($this->db);
        $c->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $datapost = $request->getParsedBody();
        $c->username = $datapost['Username'];
        $c->token = $datapost['Token'];
        $c->company_name = $datapost['Name'];
        $c->company_name_alias = $datapost['Alias'];
        $c->address = $datapost['Address'];
        $c->phone = $datapost['Phone'];
        $c->fax = $datapost['Fax'];
        $c->email = $datapost['Email'];
        $c->pic = $datapost['PIC'];
        $c->tin = $datapost['TIN'];
        $c->discount = $datapost['Discount'];
        $c->tax = $datapost['Tax'];
        $c->admin_cost = $datapost['Admin_cost'];
        $c->industryid = $datapost['IndustryID'];
        $c->salesid = $datapost['SalesID'];

        $body = $response->getBody();
        $body->write($c->add());
        return classes\Cors::modify($response,$body,200);
    });